version: '3.8'

services:
  app:
    build: 
      context: .
      dockerfile: Dockerfile
    volumes:
      - ..:/workspace:cached
      - ~/.ssh:/home/vscode/.ssh:ro  # SSH 密钥挂载（如果需要）
      
    # 防止容器自动退出
    command: sleep infinity
    
    # 环境变量
    environment:
      - PYTHONPATH=/workspace
      - PYTHON_ENV=development
      
    # 端口映射
    ports:
      - "8000:8000"  # FastAPI/Django 等Web服务
      - "8888:8888"  # Jupyter Notebook
      
    # 开发工具需要的额外功能
    init: true
    cap_add:
      - SYS_PTRACE
    security_opt:
      - seccomp:unconfined

  # PostgreSQL 数据库服务
  db:
    image: postgres:16
    environment:
      - POSTGRES_DB=devdb
      - POSTGRES_USER=devuser
      - POSTGRES_PASSWORD=devpass
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  # Redis 缓存服务
  redis:
    image: redis:7
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  postgres_data:
  redis_data: